[config.fisher]
rod_slot = "Num1"
fishes = ["honeyfin"] # fish names, case insensitive, pattern match (searches for given strings in fish name)

[config.fisher.potions]
# sonar potion slot, remove key to disable sonar potion usage. the macro does not need the sonar potion to work and can detect fishes without it
# for those who feel like telepathically knowing what fish you'll hook is cheating...
sonar_potion = "Num2"
# each potion can have their respective duration time overriden,
# this is mostly in case you use the alchemy flask's "Alchemic Enhancement" buff, which increases potion duration by 20%
# sonar_potion_duration_secs = 480 # 576 with alchemy flask buff

# having a potion's bind commented out will disable the macro"s usage of that potion
# crate_potion = "Num3"
# crate_potion_duration_secs = 240 # 288 with alchemy flask buff

# fishing_potion = "Num4"
# fishing_potion_duration_secs = 480 # 576 with alchemy flask buff

# food = "Num5" # food slot, remove key to disable food usage. useful in the `constant` seed (or worlds with the hunger system) to avoid dying of starvation.

# obtained by doing (<FOOD_BUFF_DURATION> min + 8 + 8) * 60 (on the getfixedboi seed)
# or by doing (<FOOD_BUFF_DURATION> min + 5 + 5) * 60 (on the constant seed)
# these extra 16/10 minutes are the leeway the game gives before hunger starts dealing damage. (8/5 minutes peckish, 8/5 minutes hungry)
food_duration_secs = 1440

# optional settings for overriding hotkeys, this section is not required at all
# [config.fisher.hotkeys]
# toggle = "F6" # default is "BackSlash"
# pause = "F7" # default is "RightBracket"

# optional settings for the scanner, this section is not required at all.
# do not change these settings unless you know what you're doing,
# as they can cause the scanner to not work properly (or eat up more resources than necessary)
# [config.scanner]
# poll_interval_ms = 10 # default is 25
